# Site settings
title:              Jekyllbase
email:              hej@urre.me
description:        Minimal Jekyll Starter using Basscss and Gulp
twitter_username:   urre
exclude: 			["node_modules", "gulpfile.js", "package.json", "bower_components", "gulp"]
buildtype: 			development
url:				https://github.com/urre/jekyllbase
repo: 				https://github.com/urre/jekyllbase
twittercards:		true

# Build settings
paginate:     10
markdown:    redcarpet
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"